run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: _test\.go
      linters:
        - staticcheck
      text: "should not use built-in type string as key"
    - path: internal/http/middleware\.go
      linters:
        - staticcheck
      text: "should not use built-in type string as key"
